### ISSUE TITLE
When slider is in scrollView, slider doesn't work properly

### ISSUE THREAD

**Issue by hanihashemi** [rey5137/material#206]
please check below video:

![slider](http://i.imgur.com/dG6nk2r.gif)

**Comment by rey5137** [comment]
I have published 1.2.1.1-SNAPSHOT version that contain a fix for this bug.

**Comment by hanihashemi** [comment]
thank you ;)

**Comment by Gaudon** [comment]
Has this been fixed? I still can't seem to drag sliders in a scroll view.. they move a few notches and lose focus.
